name: Hourly Sync

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - run: node scripts/sync-github.mjs
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automated sync at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        git push